### ISSUE TITLE
Patch for /trunk/pch-gadgets/TRCC/css/trcc.css

### ISSUE THREAD

**Issue by GoogleCodeExporter** [PHackett/pch-gadgets#2]
```
I think red would be a much better colour
```

Original issue reported on code.google.com by `J.G.Wils...@gmail.com` on 14 May 2013 at 12:39

Attachments:
- [trcc.css.patch](https://storage.googleapis.com/google-code-attachments/pch-gadgets/issue-2/comment-0/trcc.css.patch)

**Comment by PHackett** [comment]
Thank you for the thought, whoever you are!
